In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("car_data1.csv")
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [3]:
df.shape

(1000, 3)

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=0)

In [5]:
print(X_train)

[[    51  21500]
 [    41  45000]
 [    34 114500]
 ...
 [    61  84500]
 [    30  62000]
 [    19  45500]]


In [6]:
print(X_test)

[[    54 136500]
 [    41  67500]
 [    50  29500]
 [    20  86000]
 [    27  31500]
 [    36  48500]
 [    40  97500]
 [    51  45500]
 [    55  71500]
 [    28  89500]
 [    47  80500]
 [    19  21000]
 [    35  44500]
 [    27  31000]
 [    46  33500]
 [    49  36000]
 [    33  60000]
 [    52  67500]
 [    42 108000]
 [    34  32500]
 [    32  67500]
 [    38  58500]
 [    27  82500]
 [    51  98500]
 [    55 140500]
 [    41  72500]
 [    37  75000]
 [    39  42000]
 [    38 145500]
 [    40  43500]
 [    40  80500]
 [    41  73500]
 [    29  86500]
 [    27  88000]
 [    25  80000]
 [    37  52000]
 [    26  80500]
 [    34  72000]
 [    38  71000]
 [    58 127500]
 [    36  76500]
 [    47  23500]
 [    54  35500]
 [    38  61000]
 [    51  37500]
 [    42  77500]
 [    30  15000]
 [    40  75000]
 [    31  18500]
 [    18  82000]
 [    57 134500]
 [    34  44500]
 [    42  65000]
 [    38  65000]
 [    41  53500]
 [    48  96000]
 [    34 150500]
 [    42  53000]
 [    31  7100

In [7]:
print(y_test)

[0 0 1 0 0 0 1 0 1 0 1 0 0 0 1 1 0 0 1 0 0 0 0 1 1 1 0 0 1 0 1 0 0 0 0 0 0
 0 0 1 0 0 1 0 1 1 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0 1 0 0 0 0 1 0 0
 0 1 1 1 1 0 0 1 1 0 0 0 1 0 1 1 0 1 1 1 1 1 1 0 0 1 0 1 0 0 1 0 0 1 0 0 0
 0 0 0 0 1 0 0 1 0 0 0 0 0 1 1 0 1 1 0 0 0 0 1 1 0 1 0 0 0 1 0 1 1 0 1 0 0
 1 1 0 1 1 0 0 0 1 0 0 0 0 1 0 1 0 1 0 1 1 0 1 1 0 0 1 0 1 0 1 0 0 0 0 1 0
 0 1 1 1 0 1 0 1 1 1 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 1 0 0 1 0 1 1 0
 0 0 0 0 0 0 1 1 0 0 1 1 1 1 0 0 0 0 1 0 0 1 0 0 0 0 1 1 0 1 1 1 1 1 1 0 0
 1 0 1 1 0 1 0 1 1 1 1 1 0 1 1 1 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 1 0 1 1 0
 1 0 0 0]


In [8]:
print(y_test)

[0 0 1 0 0 0 1 0 1 0 1 0 0 0 1 1 0 0 1 0 0 0 0 1 1 1 0 0 1 0 1 0 0 0 0 0 0
 0 0 1 0 0 1 0 1 1 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0 1 0 0 0 0 1 0 0
 0 1 1 1 1 0 0 1 1 0 0 0 1 0 1 1 0 1 1 1 1 1 1 0 0 1 0 1 0 0 1 0 0 1 0 0 0
 0 0 0 0 1 0 0 1 0 0 0 0 0 1 1 0 1 1 0 0 0 0 1 1 0 1 0 0 0 1 0 1 1 0 1 0 0
 1 1 0 1 1 0 0 0 1 0 0 0 0 1 0 1 0 1 0 1 1 0 1 1 0 0 1 0 1 0 1 0 0 0 0 1 0
 0 1 1 1 0 1 0 1 1 1 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 1 0 0 1 0 1 1 0
 0 0 0 0 0 0 1 1 0 0 1 1 1 1 0 0 0 0 1 0 0 1 0 0 0 0 1 1 0 1 1 1 1 1 1 0 0
 1 0 1 1 0 1 0 1 1 1 1 1 0 1 1 1 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 1 0 1 1 0
 1 0 0 0]


In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_test)
X_test = sc.transform(X_test)


In [10]:
print(X_train)

[[ 1.36019444  1.88974463]
 [ 0.16029435 -0.15066503]
 [ 0.99099441 -1.2743689 ]
 [-1.7780058   0.39640133]
 [-1.13190575 -1.21522659]
 [-0.30120569 -0.71251697]
 [ 0.06799434  0.7364696 ]
 [ 1.08329442 -0.80123043]
 [ 1.45249445 -0.03238041]
 [-1.03960575  0.49990037]
 [ 0.71409439  0.23375998]
 [-1.87030581 -1.52572371]
 [-0.3935057  -0.83080158]
 [-1.13190575 -1.23001217]
 [ 0.62179438 -1.15608428]
 [ 0.8986944  -1.0821564 ]
 [-0.57810571 -0.37244869]
 [ 1.17559442 -0.15066503]
 [ 0.25259435  1.04696672]
 [-0.4858057  -1.18565544]
 [-0.67040572 -0.15066503]
 [-0.11660568 -0.41680542]
 [-1.13190575  0.29290228]
 [ 1.08329442  0.76604076]
 [ 1.45249445  2.00802924]
 [ 0.16029435 -0.00280926]
 [-0.20890568  0.07111863]
 [-0.02430567 -0.90472947]
 [-0.11660568  2.15588502]
 [ 0.06799434 -0.86037274]
 [ 0.06799434  0.23375998]
 [ 0.16029435  0.02676189]
 [-0.94730574  0.4111869 ]
 [-1.13190575  0.45554363]
 [-1.31650577  0.2189744 ]
 [-0.20890568 -0.60901793]
 [-1.22420576  0.23375998]
 

In [11]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train, y_train)

ValueError: Found input variables with inconsistent numbers of samples: [300, 700]